# -*- coding: utf-8 -*-
"""def_preço

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZl8pf8HHEiHzSxzdTLiUrd9Nd8ytsjE
"""

def desconto(preco , porcentagem):
  return preco - (preco * porcentagem / 100)

valor_do_desconto = desconto(100,20)
print(f"valor_do_desconto é de ${valor_do_desconto:.2f}")