# -*- coding: utf-8 -*-
"""def_soma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZl8pf8HHEiHzSxzdTLiUrd9Nd8ytsjE
"""

def soma(num1 , num2 ):
  soma = num1 + num2
  return soma

total = soma(2,5)
print(f"A resultado da soma foi {total}")