# -*- coding: utf-8 -*-
"""Dicionario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0b0hIFMFLgYZ2sNyfWg_vZzF6LFYbhj
"""

escola_do_andre = {
    "Nome": input("Digite o nome da aluno: "),
    "Idade": input("Digite a idade: "),
    "Endereço": input("Digite o endereço: ")

}

print(f"{escola_do_andre["Nome"]} tem {escola_do_andre["Idade"]} e mora em {escola_do_andre["Endereço"]}")