# -*- coding: utf-8 -*-
"""List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0b0hIFMFLgYZ2sNyfWg_vZzF6LFYbhj
"""

lista = [1,2,3,4,5]

lista.append(6)

lista.remove(2)

print(len(lista))
print(lista)