# -*- coding: utf-8 -*-
"""password

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZl8pf8HHEiHzSxzdTLiUrd9Nd8ytsjE
"""

tentativa_senha = 0
senha = "123"

while tentativa_senha < 3:
  print("Digite a senha: ")
  senha = input("Digite a senha!")
  if senha != "123":
    print("Tente denovo!")
    tentativa_senha += 1
    if tentativa_senha >= 3:
      print("Tentativas chegaram ao fim!")
  else:
    print("Correto")
    break