# -*- coding: utf-8 -*-
"""Tupla

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0b0hIFMFLgYZ2sNyfWg_vZzF6LFYbhj
"""

#isso aqui é tuplas

teste = ("teste 1 ", "teste 2 " , "teste 3 ")
print(teste)